# Generated by Django 2.2.3 on 2020-05-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='login',
            field=models.IntegerField(default=0),
        ),
    ]
