# Generated by Django 2.2.3 on 2020-08-24 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='desafio_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contato',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contatos.Categoria'),
        ),
    ]
