# Generated by Django 2.2.3 on 2020-08-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_auto_20200824_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='sql_desafio',
            field=models.IntegerField(default=0),
        ),
    ]
