# Generated by Django 2.2.3 on 2020-09-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_contato_sql_desafio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='new_code',
            field=models.CharField(blank=True, default='contatos = Contato.objects.raw(f\'SELECT * FROM contatos_contato WHERE nome LIKE "{termo[0]}"\')', max_length=350),
        ),
    ]
