# Generated by Django 2.2.3 on 2020-10-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0010_auto_20201005_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='new_senha',
        ),
    ]
