# Generated by Django 2.2.3 on 2020-10-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0012_auto_20201005_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='new_code',
            field=models.CharField(blank=True, default='dsadsadsadadgfdg', max_length=350),
        ),
        migrations.AddField(
            model_name='contato',
            name='new_header',
            field=models.CharField(blank=True, default='', max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='contato',
            name='sql_desafio',
            field=models.IntegerField(default=0),
        ),
    ]
